name: Documentation
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
    paths:
      - 'doc/**'
      - 'multi_mst/k_mst/k_mst.py'
      - 'multi_mst/noisy_mst/noisy_mst.py'
      - '.github/workflows/Docs.yml'
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        name: Install python
        with: 
          python-version: 3.9
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y pandoc
          pip install -e .

      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          cache: True
          checkout: False
          documentation_path: ./doc
          requirements_path: ./doc/requirements.txt